### ISSUE TITLE
generator not found?

### ISSUE THREAD

**Issue by matthewfischer** [RealFaviconGenerator/rails_real_favicon#19]
Followed the directions, installed the Gem with bundle, but it for some reason can't find the generator. What am I missing?

> Using rails_real_favicon 0.0.7
> Bundle complete! 17 Gemfile dependencies, 73 gems now installed.

> ubuntu@mfisch-test:~/App$ rails generate favicon
> Running via Spring preloader in process 19263
> Expected string default value for '--jbuilder'; got true (boolean)
> Expected string default value for '--helper'; got true (boolean)
> Expected string default value for '--assets'; got true (boolean)
> Could not find generator 'favicon'. Maybe you meant 'mailer', 'assets' or 'job'
> Run `rails generate --help` for more options.

**Comment by schlick** [comment]
@matthewfischer I got the same issue and discovered that it was due to my project having `zipruby` installed. `rails_real_favicon` installs `rubyzip` as a dependency and the two zip gems conflict. I temporarily removed `zipruby`, ran the favicon generator and it worked. Then I was able to put back `zipruby` and removed the `rails_real_favicon` gem entirely.

**Comment by phbernard** [comment]
I suppose we can consider this issue as closed. Googling "Could not find generator 'favicon'" leads to this page, which is a good thing.
