### ISSUE TITLE
Update to rails 5

### ISSUE THREAD

**Issue by Friend-LGA** [RealFaviconGenerator/rails_real_favicon#7]

**Comment by phbernard** [comment]
Absolutely. Do you know if there is anything to do, in addition to allowing "5" as the RoR version?

**Comment by steveclarke** [comment]
I can confirm that the generator works for me without errors using Rails 5 after removing the RoR "<5" from the gemspec.

**Comment by DannyBen** [comment]
I am also in need of a version that allows 5.
Is there a fork/branch that allows it in the gemspec, so I can test and confirm as well?

EDIT:

``` ruby
gem 'rails_real_favicon', github: 'DannyBen/rails_real_favicon', branch: 'rails5'
```

if anyone wants to test. I am testing myself, but having other upgrade issues that stop be from providing meaningful information at the moment.

**Comment by phbernard** [comment]
Thank you for your feedback and contributions!

I've just released v0.0.4, which can be installed on RoR 5. I've tested it and it works just fine.

However, there is an issue when installing the gem:

```
Bundler could not find compatible versions for gem "mime-types":
In snapshot (Gemfile.lock):
  mime-types (= 3.1)

In Gemfile:
  rails (~> 5.0.0) was resolved to 5.0.0, which depends on
    actionmailer (= 5.0.0) was resolved to 5.0.0, which depends on
      mail (>= 2.5.4, ~> 2.5) was resolved to 2.6.4, which depends on
        mime-types (< 4, >= 1.16)

  rails_real_favicon was resolved to 0.0.3, which depends on
    rest-client (~> 1.8) was resolved to 1.8.0, which depends on
      mime-types (< 3.0, >= 1.16)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

Running `bundle update` actually fixes the issue, as advertised. A simple workaround would be to change the instruction provided by RFG to say "run `bundle update`" (instead of "run `bundle install`"). But I'm not sure about this.Updating gems can have side effects. It might be a bit brutal to ask users for an update, all this for a favicon.

Another solution is to depend on rest-client 2.0. No more issue when running `bundle install`. But rest-client requires Ruby 2. In other words the gem will not work anymore with old Rails apps. Maybe not a big deal.

Any opinion about this?

**Comment by DannyBen** [comment]
Thanks!

In my opinion, installation instructions cannot say `bundle update`, and should stay as usual with `bundle install`.

I can also add that I have experienced the same bundle conflicts with other gems.

In my view - should rely on a newer version of `rest_client`, and if someone wants to use the gem with older rails, they can lock it to the older version of the gem.

I have actually reached the very same result I think in my [rails5 branch](https://github.com/RealFaviconGenerator/rails_real_favicon/compare/master...DannyBen:rails5)

**Comment by steveclarke** [comment]
I agree that `bundle update` in instructions would not be good, especially for new users who don't understand the potential repercussions. I think, as @DannyBen says that it's reasonable to expect people to be using a newer Ruby version by now. 

One side note is that, because of the way the gem works, you technically only need to use the gem once (well, once each time you update your icon/details). So after the initial `rails generate favicon` you don't really need the gem any more because the files are already in place.

**Comment by phbernard** [comment]
Sounds great to me. Latest v0.0.5 can be installed without warning on Rails 5. Bye Ruby 1.x :)

**Comment by DannyBen** [comment]
Excellent, thanks.
